# Generated by Django 3.2.10 on 2022-06-18 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodct',
            new_name='Product',
        ),
    ]
